# Generated by Django 2.1.7 on 2020-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(default='手机号后四位即为用户ID', max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
