# Generated by Django 2.1.7 on 2020-04-14 08:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People1',
            fields=[
                ('orderId', models.AutoField(max_length=128, primary_key=True, serialize=False, verbose_name=django.contrib.auth.models.User)),
                ('p_name', models.CharField(db_index=True, max_length=200)),
                ('P_gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')])),
                ('p_phonenum', models.CharField(max_length=30)),
                ('p_address', models.CharField(default='（乌鲁木齐市XX区XX街道XX小区XX栋XX号）', max_length=200)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='时间')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('p_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
    ]
